from pprint import pprint
import csv

trackdata = {
  'Alex': [{'Added By': 'shinditzu',
           'Album': 'Birthmarks (Deluxe Edition)',
           'Artist': 'Born Ruffians',
           'Time Added': '2025-09-01T15:10:02Z',
           'Track': 'Cherry Wine',
           'Track ID': '3blghPDiOAX3h7F5QzPWjV'},
          {'Added By': 'shinditzu',
           'Album': 'Get out the Lotion',
           'Artist': 'Low Cut Connie',
           'Time Added': '2025-09-04T22:22:18Z',
           'Track': 'Big Thighs, Nj',
           'Track ID': '2ZqjkcgIoFmKiUnZCyltTz'},
          {'Added By': 'shinditzu',
           'Album': 'O My Heart',
           'Artist': 'Mother Mother',
           'Time Added': '2025-09-04T22:22:34Z',
           'Track': 'Hayloft',
           'Track ID': '2kKkl59fY6Cic1CmhvSEZK'},
          {'Added By': 'shinditzu',
           'Album': 'High N Low',
           'Artist': 'Aquifer',
           'Time Added': '2025-09-09T12:34:46Z',
           'Track': 'High N Low',
           'Track ID': '1swi7ZorW1B9VxESxuW7d6'},
          {'Added By': 'shinditzu',
           'Album': 'Time Machine',
           'Artist': 'D.A. Wallach',
           'Time Added': '2025-09-09T13:07:01Z',
           'Track': 'Disaster',
           'Track ID': '1387vgNIuxDrOdsPXpC8Rx'}],
 'Aly': [{'Added By': 'goodwi46',
          'Album': 'The Fool (Deluxe)',
          'Artist': 'Ryn Weaver',
          'Time Added': '2025-09-13T14:25:20Z',
          'Track': 'Pierre - Siren Sessions Version',
          'Track ID': '7fSatoGqSIiJqxhLoiKfNG'},
         {'Added By': 'goodwi46',
          'Album': 'Bank On The Funeral',
          'Artist': 'Matt Maeson',
          'Time Added': '2025-09-13T14:29:26Z',
          'Track': 'Legacy',
          'Track ID': '373CjBoI0zDFNIXm57NdOY'},
         {'Added By': 'goodwi46',
          'Album': '"U"',
          'Artist': 'Malachi Nassér',
          'Time Added': '2025-09-13T14:29:49Z',
          'Track': '"U"',
          'Track ID': '2LdBAbLwbA7zPg9hRXCpjf'},
         {'Added By': 'goodwi46',
          'Album': 'Michigan Skies',
          'Artist': 'Song House',
          'Time Added': '2025-09-13T14:36:02Z',
          'Track': 'Michigan Skies',
          'Track ID': '47lkuJjIx52bWPKfB1BEzQ'},
         {'Added By': 'goodwi46',
          'Album': '3AM',
          'Artist': 'Grace Alexandra',
          'Time Added': '2025-09-13T14:36:37Z',
          'Track': '3AM',
          'Track ID': '1Mnn1SUK1IL98FpX1dIE73'},
         {'Added By': 'goodwi46',
          'Album': 'Stitch up Your Jeans',
          'Artist': 'Jack Robinson',
          'Time Added': '2025-09-13T14:37:05Z',
          'Track': 'Stitch up Your Jeans',
          'Track ID': '5dnbllS8mw5oMnPvhPfynh'},
         {'Added By': 'goodwi46',
          'Album': 'Version',
          'Artist': 'Mark Ronson',
          'Time Added': '2025-09-13T14:38:03Z',
          'Track': 'Valerie (feat. Amy Winehouse) - Version Revisited',
          'Track ID': '6kopmMZiyLmw7h66uXcXR7'},
         {'Added By': 'goodwi46',
          'Album': '9 To 5 And Odd Jobs',
          'Artist': 'Dolly Parton',
          'Time Added': '2025-09-13T14:39:08Z',
          'Track': '9 to 5',
          'Track ID': '4w3tQBXhn5345eUXDGBWZG'},
         {'Added By': 'goodwi46',
          'Album': 'Life in Cartoon Motion',
          'Artist': 'MIKA',
          'Time Added': '2025-09-13T14:39:29Z',
          'Track': 'Grace Kelly',
          'Track ID': '7dzUZec5MnWMyQnk5klnKR'}],
 'Doc': [{'Added By': 'swbernstel',
          'Album': 'Another Way to Fly',
          'Artist': 'The Sidh',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Shake That Bagpipe',
          'Track ID': '13mFHw8vgUBOD5nAtS4uSa'},
         {'Added By': 'swbernstel',
          'Album': "Didn't It Rain",
          'Artist': 'Hugh Laurie',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': "The Weed Smoker's Dream",
          'Track ID': '5OrAlk81UJzAoRycNphAY7'},
         {'Added By': 'swbernstel',
          'Album': 'Transcendental Cha Cha Cha',
          'Artist': 'Tom Cardy',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Transcendental Cha Cha Cha',
          'Track ID': '1gaa0N2DGSLKcW7aIQu9xF'},
         {'Added By': 'swbernstel',
          'Album': 'Let Them Talk',
          'Artist': 'Hugh Laurie',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': "You Don't Know My Mind",
          'Track ID': '3YwHkFhsCB9WARodNJcERE'},
         {'Added By': 'swbernstel',
          'Album': "Beth Yw'r Haf i Mi",
          'Artist': 'Gareth Rees',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': "Beth Yw'r Haf i Mi",
          'Track ID': '3tVJ3OSVfJ5Lhk172HftXX'},
         {'Added By': 'swbernstel',
          'Album': 'Falling To Pieces',
          'Artist': 'Krashkarma',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Falling To Pieces',
          'Track ID': '4axl7Me6ahtA7ivOA02lg6'},
         {'Added By': 'swbernstel',
          'Album': "Brendon Small's Galaktikon",
          'Artist': 'Brendon Small',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Beastblade',
          'Track ID': '6KmybqIXsIgHdMearl0SV7'},
         {'Added By': 'swbernstel',
          'Album': 'Californication (Deluxe Edition)',
          'Artist': 'Red Hot Chili Peppers',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Otherside',
          'Track ID': '64BbK9SFKH2jk86U3dGj2P'},
         {'Added By': 'swbernstel',
          'Album': 'Strong',
          'Artist': 'Kira Michele',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Strong',
          'Track ID': '5WekFwVyu5erogVDNQEUxB'},
         {'Added By': 'swbernstel',
          'Album': 'Mistakes',
          'Artist': 'Masetti',
          'Time Added': '2025-09-03T03:45:34Z',
          'Track': 'Mistakes',
          'Track ID': '2RmVdUI3qIixHQ1HsgQnhr'}],
 'Jack': [],
 'Jenny': [{'Added By': 'xjenbeanx',
            'Album': 'Old Phone',
            'Artist': 'Ed Sheeran',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'Old Phone',
            'Track ID': '2QxviKpVdEXKDWs706MUZB'},
           {'Added By': 'xjenbeanx',
            'Album': 'Spotify Singles',
            'Artist': 'Taylor Swift',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'September - Recorded at The Tracking Room Nashville',
            'Track ID': '5eGX87IiKsGuzS3iw4CfCX'},
           {'Added By': 'xjenbeanx',
            'Album': 'Deeper Well',
            'Artist': 'Kacey Musgraves',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'Deeper Well',
            'Track ID': '333XFHKsHU0pOocFzBgrJi'},
           {'Added By': 'xjenbeanx',
            'Album': 'Chemtrails Over The Country Club',
            'Artist': 'Lana Del Rey',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'Chemtrails Over The Country Club',
            'Track ID': '7bPWdJgx8vek7S5i5yAtvG'},
           {'Added By': 'xjenbeanx',
            'Album': 'More Adventurous (U.S. Release)',
            'Artist': 'Rilo Kiley',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'Accidntel Deth',
            'Track ID': '7KJymi3dZGLPvxmOYyWwxz'},
           {'Added By': 'xjenbeanx',
            'Album': 'A Matter of Time',
            'Artist': 'Laufey',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'Clean Air',
            'Track ID': '5vUwvYW5fpHrwHfirVpkHn'},
           {'Added By': 'xjenbeanx',
            'Album': 'I Shouldn’t Be Telling You This',
            'Artist': 'Jeff Goldblum & The Mildred Snitzer Orchestra',
            'Time Added': '2025-09-06T01:55:03Z',
            'Track': 'The Thrill Is Gone / Django (with Miley Cyrus)',
            'Track ID': '0xgMLcdtDFTgUJYVJc1vgu'},
           {'Added By': 'xjenbeanx',
            'Album': 'Bathtub Gin',
            'Artist': "The Speakeasies' Swing Band!",
            'Time Added': '2025-09-16T00:30:23Z',
            'Track': 'Liquid Paradise',
            'Track ID': '6cEbzxUwsbsWQtH4ZstR1k'}],
 'Tré': [{'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'Ocean Eyes',
          'Artist': 'Owl City',
          'Time Added': '2025-09-07T15:07:38Z',
          'Track': 'Fireflies',
          'Track ID': '3DamFFqW32WihKkTVlwTYQ'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'Fitz and The Tantrums (Deluxe Edition)',
          'Artist': 'Fitz and The Tantrums',
          'Time Added': '2025-09-07T15:07:44Z',
          'Track': 'HandClap',
          'Track ID': '4qRaZYiaOsSvWC7VgcxrI0'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'Super Powered Love',
          'Artist': 'Kirby Krackle',
          'Time Added': '2025-09-07T15:07:50Z',
          'Track': 'Booty Do Math',
          'Track ID': '7u7sktWugFCyysc6R1uhCQ'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'If I Had $150,000',
          'Artist': 'Carolina Mic',
          'Time Added': '2025-09-07T15:07:54Z',
          'Track': 'If I Had $150,000',
          'Track ID': '1z7niMiIbvun4LvAu0mwTt'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'Young Black & Rich',
          'Artist': 'Melly Mike',
          'Time Added': '2025-09-07T15:07:57Z',
          'Track': 'Young Black & Rich',
          'Track ID': '2QWin1zM9hxG9zsApuIvso'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'Toxicity',
          'Artist': 'System Of A Down',
          'Time Added': '2025-09-07T15:08:03Z',
          'Track': 'Toxicity',
          'Track ID': '0snQkGI5qnAmohLE7jTsTn'},
         {'Added By': '71fg5vzz2r72fuaevr48h6usr',
          'Album': 'The Best Of Everything - The Definitive Career Spanning '
                   'Hits Collection 1976-2016',
          'Artist': 'Tom Petty',
          'Time Added': '2025-09-07T15:09:12Z',
          'Track': "Runnin' Down A Dream",
          'Track ID': '5yAu4njFSdM47dfsTkQPZ2'}]}

clean_trackdata = []

for name, tracklist in trackdata.items():
    for track in tracklist:
        clean_trackdata.append(track)

pprint(clean_trackdata)

with open('trackdata.csv', 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['Track', 'Album', 'Artist', 'Added By', 'Time Added', 'Track ID'])
    for track in clean_trackdata:
        writer.writerow([track['Track'], track['Album'], track['Artist'],  track['Added By'], track['Time Added'], track['Track ID']])

